name: release
inputs:
  variant:
    required: true
  archs:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && tree .
    - uses: sigstore/cosign-installer@main
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        empty-workspace: false
        archs: ${{ inputs.archs }}
    - uses: distroless/actions/apko-snapshot@main
      with:
        config: apko.yaml
        base-tag: ghcr.io/${{ github.repository }}/${{ inputs.variant }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: ${{ inputs.archs }}
