name: release
inputs:
  variant:
    required: true
  archs:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github" >> .melangeignore && tree .
    - uses: sigstore/cosign-installer@main
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        empty-workspace: false
        archs: ${{ inputs.archs }}
    - uses: distroless/actions/apko-snapshot@main
      with:
        config: apko.yaml
        base-tag: ghcr.io/${{ github.repository }}/${{ inputs.variant }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: ${{ inputs.archs }}
    - name: Smoke test
      shell: bash
      run: |
        ref="ghcr.io/${{ github.repository }}/${{ inputs.variant }}"
        docker pull "${ref}"
        docker run -d --rm -p 8080:8080 --name smoketest "${ref}"
        trap "docker rm -f smoketest" EXIT
        sleep 5 # Give server a few seconds to come up
        curl -v --max-time 10 http://localhost:8080/ | grep 'Hello World!'
