name: py-presubmit
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/actions/presubmit-variant/action.yml
      - .github/workflows/py-presubmit.yml
      - py/**
jobs:
  build:
    name: Verify Python variant image (single arch)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/presubmit-variant
        with:
          variant: py
          archs: amd64
